    development:
        :address: smtp.gmail.com
        :port: 587
        :authentication: plain
        :user_name: casddir@gmail.com
        :password: apdalua
        :enable_starttls_auto: true
    production:
        :address: smtp.gmail.com
        :port: 587
        :authentication: plain
        :user_name: casddir@gmail.com
        :password: apdalua
        :enable_starttls_auto: true